check:
  image: debian:buster
  interruptible: true
  allow_failure: true
  tags:
    - lightweight
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends
        ca-certificates
        python3-gitlab
        python3-yaml
  script:
    - ./gitlab-rulez
        --gitlab-api-token "$RULEZ_GITLAB_API_TOKEN"
        --gitlab-server-url "$CI_SERVER_URL"
        diff rulez.yaml
